filebeat.inputs:
  - type: filestream
    id: my-filestream-id
    enabled: true
    paths:
      - "/var/log/server/*.log"
output.logstash:
  hosts: ["logstash:5044"]
#processors:
#  - add_docker_metadata:
#      host: "unix:///host_docker/docker.sock"